### ISSUE TITLE
戻るボタンでトップページに戻る機能を実装

### ISSUE THREAD

**Issue by nkthkr** [Kenny-NISLab/nisplan#10]
## 実施内容
- pagesに下層ページのファイル作成(中身は空でも良い)
- BackPage.vueを子に持つ「戻るボタンコンポーネント」の作成
- "nuxt-link"でトップページに戻る機能を実装

## Tips
- SVGのコンポーネントはファイル名でSVGであることを分かるように命名するか、components/svgみたいなフォルダを作成しておくと良い(フォルダを作成する場合はimport等を記述する必要が出てくる)
- transitionを使ってページ遷移をおしゃれにもできる(追々でも可)

**Comment by nkthkr** [comment]
ついでに右下の予定追加ボタンでページ遷移できる機能も実装しちゃっていいかも

**Comment by uzumal** [comment]
> SVGのコンポーネントはファイル名でSVGであることを分かるように命名するか、components/svgみたいなフォルダを作成しておくと良い(フォルダを作成する場合はimport等を記述する必要が出てくる)

NISPLANのロゴをsvgとして読み込むイメージで合ってますか？？？

**Comment by nkthkr** [comment]
> NISPLANのロゴをsvgとして読み込むイメージで合ってますか？？？

それはどっちでも良い。
今だとcomponents/BackPage.vueが実質svgのみのファイルやからcomponents/svgs/...みたいにするかLeftArrowSVG.vueみたいにした方が後から何のコンポーネントかわかりやすいって感じ。
あくまでも自論でDX(Developer Experience)のためのもの🧐

**Comment by uzumal** [comment]
> 実質svgのみのファイルやから

機能のないコンポーネントだからsvgと見立てて分かりやすくするってことですね！理解です、ありがとうございますっ！
