### ISSUE TITLE
APIデータのstore格納方法

### ISSUE THREAD

**Issue by uzumal** [Kenny-NISLab/nisplan#13]
### Studentsの格納が分かりません…
現時点での記述分です
```
export const state = () => ({
  students: [],
})

export const mutations = {
  setStudents(state, students) {
    state.students = students
  },
}

export const actions = {
  async getStudents({ commit }, $config) {
    const res = await this.$axios
      .$get($config.apiUrl + '/students')
      .then(
        // headers: { 'x-api-key': $config.apiKey }
        commit('setStudents', res.data.Items)
      )
      .catch(
        commit(
          'setStudents',
          Array(23).fill({
            id: 0,
            j_last_name: 'Not',
            j_first_name: 'Found',
            avatar: require('@/assets/images/defaultAvatar.jpg'),
            is_stay: false,
          })
        )
      )
  },
}

```
とりあえずいろんなサイトを参考に書こうとしたのですが、お門違いなことしてそうです。
actionでasync awaitでgetしようとしたのですが、

- $configの書く位置
- headersが読み込まれない($configが参照できていないため？)
- thenでのcommitのresが読み込まれない(そもそも書き方が違う？)

の3点が特に分かりません😢
アドバイスお願いします🙇‍♂️

**Comment by nkthkr** [comment]
> $configの書く位置
```
async getStudents({ commit , $config }) {
```
通常はこの位置、だけどstore/index.jsでは$configを読み込めないので、中でthis.$config.~で直接指定しておく。

> headersが読み込まれない

headerの書く位置が違う。
```
.get(this.$config.apiUrl + '/students', {
    headers: { 'x-api-key': this.$config.apiKey },
})
```

> thenでのcommitのresが読み込まれない
```
.then((res) => {
　　//処理
})
```
こんな感じでresにgetしたデータが入ってそれを使って中で処理をする。

**Comment by nkthkr** [comment]
Chromeのvue devtoolsの左から2番目のタブでstoreの情報がみれるからそこ確認しながらやると良いかも。

**Comment by nkthkr** [comment]
一応こっちで動くやつはできたからまた困ったら追記して、zoomなどでも可

**Comment by uzumal** [comment]
> 一応こっちで動くやつはできたからまた困ったら追記して、zoomなどでも可

ありがとうございます🙇‍♂️
storeに値を格納する形まではできたんですが、実際に値が入ってないっぽくて、またそれをgetterで取り出そうとしてるんですが、配列の中身全部を取り出せない状況です…

zoomできそうなら少しだけお話聞きたいです！
