### ISSUE TITLE
Weather配列のオブジェクトに参照できない

### ISSUE THREAD

**Issue by uzumal** [Kenny-NISLab/nisplan#32]
OpenWeatherMap APIで配列取得しているが、配列内のオブジェクトを参照できない

**Comment by uzumal** [comment]
おそらく描画前にAPIからデータを受け切れてなかったことが原因ぽかったです…
v-ifを用いることで治ったので、再度プルリクします
治ったコード
`    <h1 v-if="Weather2[0].temp">{{ Weather2[0].temp.min }}</h1>
`

**Comment by nkthkr** [comment]
[Vueライフサイクルの盲点、computedの一発目の発火はmountedより早い](https://qiita.com/techneconn/items/c5e85574ef792b3fbad2)

多分ここら辺が関係ありそうやな〜、dispatchをmountedからcreatedに変えていけんかな
