### ISSUE TITLE
テーマ切り替えのボタン設置の検討

### ISSUE THREAD

**Issue by nkthkr** [Kenny-NISLab/nisplan#36]
どこにトグルボタン設置しようか？
ユーザー登録ないしPWAのキャッシュイマイチ分からんからOSの設定にデフォルトのテーマ合わせるだけならボタンはなくても良いかな

**Comment by uzumal** [comment]
確かにトグルしても保持しない可能性ありそうですね…
ボタンは保留で良さそうです！

**Comment by nkthkr** [comment]
多分着手可
