### ISSUE TITLE
ListStudentの開発

### ISSUE THREAD

**Issue by uzumal** [Kenny-NISLab/nisplan#6]
### ToDO
- [x] defaultの表示(レイアウト込み)
- [x] Schedule取得
- [x] リファクタリング

### 上手くいかない点
- defaultのavatarのデータを取得しているが、画像が表示されない

**Comment by nkthkr** [comment]
> defaultのavatarのデータを取得しているが、画像が表示されない

v-bind:srcで指定する時は工夫がいるみたい
https://qiita.com/hiroyukiwk/items/a26e767d193ef8d9155b

**Comment by kogepanh** [comment]
これ一度はみんな詰まるよなあ

**Comment by uzumal** [comment]
> これ一度はみんな詰まるよなあ

登竜門的な存在なんですね（笑）
