### ISSUE TITLE
バグ修正のリリース出しとく？

### ISSUE THREAD

**Issue by nkthkr** [Kenny-NISLab/nisplan#97]
最後までスクロールしたところの余白にバージョン情報出してもいいかもね

**Comment by uzumal** [comment]
> 最後までスクロールしたところの余白にバージョン情報出してもいいかもね

現在のリリース削除して、リリース出しておきますか？
バージョンは、コピーライトとかとは違う認識でいいですか…？

**Comment by nkthkr** [comment]
> 現在のリリース削除して、リリース出しておきますか？
バージョンは、コピーライトとかとは違う認識でいいですか…？

リリースは削除するもんじゃないとは思う
v1.0.0時点でバグがあったからそれを修正しましたよって感じのv1.0.1みたいなイメージ？(正式にはリリース時にはバグなかったけど)
コピーライトとは違う、個人的にはフッターにリリースタグ載せとけばアップデート追いやすいかなーって

**Comment by uzumal** [comment]
そうなんですね！リリースしておきます！
なるほど、、またやっておきます〜
